
package com.company.servicioweb.serviciologeo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpringWebLogeoServicio", targetNamespace = "http://com/company/servicioweb/servicioLogeo")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.company.servicioweb.serviciologeo.ObjectFactory.class,
    com.company.servicioweb.usuario.ObjectFactory.class
})
public interface SpringWebLogeoServicio {


    /**
     * 
     * @param rolesRequest
     * @return
     *     returns com.company.servicioweb.serviciologeo.RolesResponse
     */
    @WebMethod(operationName = "Roles")
    @WebResult(name = "RolesResponse", targetNamespace = "http://com/company/servicioweb/servicioLogeo", partName = "RolesResponse")
    public RolesResponse roles(
        @WebParam(name = "RolesRequest", targetNamespace = "http://com/company/servicioweb/servicioLogeo", partName = "RolesRequest")
        RolesRequest rolesRequest);

    /**
     * 
     * @param logeoRequest
     * @return
     *     returns com.company.servicioweb.serviciologeo.LogeoResponse
     */
    @WebMethod(operationName = "Logeo")
    @WebResult(name = "LogeoResponse", targetNamespace = "http://com/company/servicioweb/servicioLogeo", partName = "LogeoResponse")
    public LogeoResponse logeo(
        @WebParam(name = "LogeoRequest", targetNamespace = "http://com/company/servicioweb/servicioLogeo", partName = "LogeoRequest")
        LogeoRequest logeoRequest);

}
