
package com.company.servicioweb.serviciologeo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpringWebLogeoServicios", targetNamespace = "http://com/company/servicioweb/servicioLogeo", wsdlLocation = "http://localhost:8090/servicio/SpringWebLogeoServicio.wsdl")
public class SpringWebLogeoServicios
    extends Service
{

    private final static URL SPRINGWEBLOGEOSERVICIOS_WSDL_LOCATION;
    private final static WebServiceException SPRINGWEBLOGEOSERVICIOS_EXCEPTION;
    private final static QName SPRINGWEBLOGEOSERVICIOS_QNAME = new QName("http://com/company/servicioweb/servicioLogeo", "SpringWebLogeoServicios");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/servicio/SpringWebLogeoServicio.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPRINGWEBLOGEOSERVICIOS_WSDL_LOCATION = url;
        SPRINGWEBLOGEOSERVICIOS_EXCEPTION = e;
    }

    public SpringWebLogeoServicios() {
        super(__getWsdlLocation(), SPRINGWEBLOGEOSERVICIOS_QNAME);
    }

    public SpringWebLogeoServicios(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPRINGWEBLOGEOSERVICIOS_QNAME, features);
    }

    public SpringWebLogeoServicios(URL wsdlLocation) {
        super(wsdlLocation, SPRINGWEBLOGEOSERVICIOS_QNAME);
    }

    public SpringWebLogeoServicios(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPRINGWEBLOGEOSERVICIOS_QNAME, features);
    }

    public SpringWebLogeoServicios(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpringWebLogeoServicios(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SpringWebLogeoServicio
     */
    @WebEndpoint(name = "SpringWebLogeoServicioSoap11")
    public SpringWebLogeoServicio getSpringWebLogeoServicioSoap11() {
        return super.getPort(new QName("http://com/company/servicioweb/servicioLogeo", "SpringWebLogeoServicioSoap11"), SpringWebLogeoServicio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpringWebLogeoServicio
     */
    @WebEndpoint(name = "SpringWebLogeoServicioSoap11")
    public SpringWebLogeoServicio getSpringWebLogeoServicioSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/company/servicioweb/servicioLogeo", "SpringWebLogeoServicioSoap11"), SpringWebLogeoServicio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPRINGWEBLOGEOSERVICIOS_EXCEPTION!= null) {
            throw SPRINGWEBLOGEOSERVICIOS_EXCEPTION;
        }
        return SPRINGWEBLOGEOSERVICIOS_WSDL_LOCATION;
    }

}
